---
services:
  master-slave-app-js:
    build: .
    container_name: master-slave-app-js
    image: master-slave-app-js:1.0.0
    ports:
      - "8002:8002"
    mem_limit: 256m
    cpus: 1
    environment:
      - APP_PORT=8002
      - DB_NAME=simple_app

      - DB_WRITE_HOST=mariadb-master
      - DB_WRITE_PORT=3306
      - DB_WRITE_CONNECTION_LIMIT=10
      - DB_WRITE_TIMEOUT=10000
      - DB_WRITE_USER=root
      - DB_WRITE_PASSWORD=secret

      - DB_READ_HOST=mariadb-slave2
      - DB_READ_PORT=3306
      - DB_READ_CONNECTION_LIMIT=10
      - DB_READ_TIMEOUT=10000
      - DB_READ_USER=readonlyuser
      - DB_READ_PASSWORD=readonlypass
    networks:
     - mariadb-master-slave-network

networks:
  mariadb-master-slave-network:
    driver: bridge
    external: true